# pandas Concat

In [2]:
import pandas as pd

Bd_weather = pd.DataFrame({
    'city' : ['Dhaka','Rajshahi','khulna'],
    'temperature':[32,45,30],
    'humidity':[80,60,78]
})

Bd_weather

       city  temperature  humidity
0     Dhaka           32        80
1  Rajshahi           45        60
2    khulna           30        78

In [3]:

Us_weather = pd.DataFrame({
    'city' : ['New york','chicago','orlando'],
    'temperature':[21,14,35],
    'humidity':[68,65,75]
})

Us_weather

       city  temperature  humidity
0  New york           21        68
1   chicago           14        65
2   orlando           35        75

In [5]:
pd.concat([Bd_weather, Us_weather])

       city  temperature  humidity
0     Dhaka           32        80
1  Rajshahi           45        60
2    khulna           30        78
0  New york           21        68
1   chicago           14        65
2   orlando           35        75

In [6]:
pd.concat([Bd_weather, Us_weather],ignore_index=True)

       city  temperature  humidity
0     Dhaka           32        80
1  Rajshahi           45        60
2    khulna           30        78
3  New york           21        68
4   chicago           14        65
5   orlando           35        75

# keys

In [9]:
df = pd.concat([Bd_weather, Us_weather], keys=["Bangladesh","us"])
df

                  city  temperature  humidity
Bangladesh 0     Dhaka           32        80
           1  Rajshahi           45        60
           2    khulna           30        78
us         0  New york           21        68
           1   chicago           14        65
           2   orlando           35        75

In [10]:
df.loc["Bangladesh"]

       city  temperature  humidity
0     Dhaka           32        80
1  Rajshahi           45        60
2    khulna           30        78

In [11]:
df.loc["us"]

       city  temperature  humidity
0  New york           21        68
1   chicago           14        65
2   orlando           35        75

In [14]:
temperature_df = pd.DataFrame({
   'city' : ['Dhaka','Rajshahi','khulna'],
    'temperature':[32,45,30],
})

temperature_df

       city  temperature
0     Dhaka           32
1  Rajshahi           45
2    khulna           30

In [15]:
windspeed_df =pd.DataFrame(  {
     'city' : ['Dhaka','Rajshahi','khulna'],
    'windspeed':[7,12,9],
})
windspeed_df

       city  windspeed
0     Dhaka          7
1  Rajshahi         12
2    khulna          9

In [19]:
df = pd.concat([
temperature_df, windspeed_df])
df

       city  temperature  windspeed
0     Dhaka         32.0        NaN
1  Rajshahi         45.0        NaN
2    khulna         30.0        NaN
0     Dhaka          NaN        7.0
1  Rajshahi          NaN       12.0
2    khulna          NaN        9.0

In [20]:
df = pd.concat([
temperature_df, windspeed_df],axis=1)
df

       city  temperature      city  windspeed
0     Dhaka           32     Dhaka          7
1  Rajshahi           45  Rajshahi         12
2    khulna           30    khulna          9

In [21]:
temperature_df

       city  temperature
0     Dhaka           32
1  Rajshahi           45
2    khulna           30

In [24]:
s = pd.Series(["Humid","Dry","Rain"], name="event")
s

0    Humid
1      Dry
2     Rain
Name: event, dtype: object

In [25]:
pd.concat([temperature_df, s] , axis=1)

       city  temperature  event
0     Dhaka           32  Humid
1  Rajshahi           45    Dry
2    khulna           30   Rain