# https://pythonspeed.com/articles/pandas-load-less-data/

# Reducing Pandas memory usage lossless compressiion

# Technique 1 : Don't load all columns

In [1]:

import pandas as pd
import numpy as np

df = pd.read_csv('/home/catpc/Downloads/weather_data_3city.csv')
df

         day      city  temperature  windspeed   event
0   01/01/25  new york           32          6    Rain
1   01/02/25  new york           36          7   Sunny
2   01/03/25  new york           28         12    Snow
3   01/04/25  new york           33          7   Sunny
4   01/01/25    mumbai           90          5   Sunny
5   01/02/25    mumbai           85         12     Fog
6   01/03/25    mumbai           87         15     Fog
7   01/04/25    mumbai           92          5    Rain
8   01/01/25     paris           45         20   Sunny
9   01/02/25     paris           50         13  Cloudy
10  01/03/25     paris           54          8  Cloudy
11  01/04/25     paris           42         10  Cloudy

In [2]:
df.info(verbose=False, memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Columns: 5 entries, day to event
dtypes: int64(2), object(3)
memory usage: 2.5 KB

In [3]:
df = df[['city','event']]
df.info(verbose=False, memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Columns: 2 entries, city to event
dtypes: object(2)
memory usage: 1.6 KB

# Technique 2 : shrink numerical columns with smaller dtypes

In [10]:

import pandas as pd
import numpy as np

df = pd.read_csv('/home/catpc/Downloads/weather_data_3city.csv')
df

         day      city  temperature  windspeed   event
0   01/01/25  new york           32          6    Rain
1   01/02/25  new york           36          7   Sunny
2   01/03/25  new york           28         12    Snow
3   01/04/25  new york           33          7   Sunny
4   01/01/25    mumbai           90          5   Sunny
5   01/02/25    mumbai           85         12     Fog
6   01/03/25    mumbai           87         15     Fog
7   01/04/25    mumbai           92          5    Rain
8   01/01/25     paris           45         20   Sunny
9   01/02/25     paris           50         13  Cloudy
10  01/03/25     paris           54          8  Cloudy
11  01/04/25     paris           42         10  Cloudy

In [11]:
df['temperature'].memory_usage(index=False,deep=True)

96

In [12]:
df['temperature'].max()

92

In [13]:
df['temperature'].min()

28

In [16]:
df = pd.read_csv('/home/catpc/Downloads/weather_data_3city.csv',
                dtype={'temperature':'int8'}
                )


df['temperature'].memory_usage(index=False, deep=True)

12

# Technique3: shrink categorical data using categorical dtypes

In [19]:
set(df['event'])
df['event'].memory_usage(index=False, deep=True)

740