# Merge DataFrame

In [26]:
import pandas as pd

df1 = pd.DataFrame({
    'city' : ["new york","chicago","orlando"],
    'temperature':[21, 14, 35]
    
})


df1

       city  temperature
0  new york           21
1   chicago           14
2   orlando           35

In [27]:
df2 = pd.DataFrame({
    'city' : ["chicago","new york","orlando"],
    'humidity':[65,68,75]
    
})

df2

       city  humidity
0   chicago        65
1  new york        68
2   orlando        75

In [29]:
pd.merge(df1,df2,on="city")

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [34]:


df1 = pd.DataFrame({
    'city' : ["new york","chicago","orlando","bultimol"],
    'temperature':[21, 14, 35,45]
    
})


df1

       city  temperature
0  new york           21
1   chicago           14
2   orlando           35
3  bultimol           45

In [32]:
df2 = pd.DataFrame({
    'city' : ["chicago","new york","sunfrisco"],
    'humidity':[65,68,75]
    
})

df2

        city  humidity
0    chicago        65
1   new york        68
2  sunfrisco        75

In [39]:
df3 = pd.merge(df1,df2, on="city",how="outer")
df3

        city  temperature  humidity
0   bultimol         45.0       NaN
1    chicago         14.0      65.0
2   new york         21.0      68.0
3    orlando         35.0       NaN
4  sunfrisco          NaN      75.0

In [40]:
df4 = pd.merge(df1,df2, on="city",how="left")
df4

       city  temperature  humidity
0  new york           21      68.0
1   chicago           14      65.0
2   orlando           35       NaN
3  bultimol           45       NaN

In [41]:
df4 = pd.merge(df1,df2, on="city",how="right")
df4

        city  temperature  humidity
0    chicago         14.0        65
1   new york         21.0        68
2  sunfrisco          NaN        75

In [42]:
df4 = pd.merge(df1,df2, on="city",how="inner")
df4

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65

# use indicator flag in join

In [43]:
df5 = pd.merge(df1,df2, on="city",how="outer" , indicator= True)

df5

        city  temperature  humidity      _merge
0   bultimol         45.0       NaN   left_only
1    chicago         14.0      65.0        both
2   new york         21.0      68.0        both
3    orlando         35.0       NaN   left_only
4  sunfrisco          NaN      75.0  right_only

In [45]:
df6 = pd.DataFrame({
    'city':['new york','chicago','orlando','baltimore'],
    'temperature':[21,14,35,38],
    'humidity':[65,68,71,75]
})

df6

        city  temperature  humidity
0   new york           21        65
1    chicago           14        68
2    orlando           35        71
3  baltimore           38        75

In [46]:
df7 = pd.DataFrame({
    'city':['chicago','new york','sun dego'],
    'temperature':[21,14,35],
    'humidity':[65,68,71]
})

df7

       city  temperature  humidity
0   chicago           21        65
1  new york           14        68
2  sun dego           35        71

In [47]:
pd.merge(df6,df7,on='city')

       city  temperature_x  humidity_x  temperature_y  humidity_y
0  new york             21          65             14          68
1   chicago             14          68             21          65

In [51]:
res = pd.merge(df6,df7,on='city', suffixes=( '_left','_right'))
res

,city,temperature_left,humidity_left,temperature_right,humidity_right
0,new york,21,65,14,68
1,chicago,14,68,21,65