# Pivot

# pivot allows you to transform or reshape data

In [1]:

import pandas as pd
import numpy as np

df = pd.read_csv('/home/catpc/Downloads/weather_data_3city.csv')
df

         day      city  temperature  windspeed   event
0   01/01/25  new york           32          6    Rain
1   01/02/25  new york           36          7   Sunny
2   01/03/25  new york           28         12    Snow
3   01/04/25  new york           33          7   Sunny
4   01/01/25    mumbai           90          5   Sunny
5   01/02/25    mumbai           85         12     Fog
6   01/03/25    mumbai           87         15     Fog
7   01/04/25    mumbai           92          5    Rain
8   01/01/25     paris           45         20   Sunny
9   01/02/25     paris           50         13  Cloudy
10  01/03/25     paris           54          8  Cloudy
11  01/04/25     paris           42         10  Cloudy

In [2]:
df.pivot(index='day', columns='city', values='temperature')

city      mumbai  new york  paris
day
01/01/25      90        32     45
01/02/25      85        36     50
01/03/25      87        28     54
01/04/25      92        33     42

# pivot table is used to summarize and aggregate data inside dataframe

In [3]:
df = pd.DataFrame([
    {'date':'5/1/2025','city':'new york','temperature':65,'humidity':56},
    {'date':'5/1/2025','city':'new york','temperature':61,'humidity':54},
    {'date':'5/2/2025','city':'new york','temperature':70,'humidity':60},
    {'date':'5/2/2025','city':'new york','temperature':72,'humidity':62},
    {'date':'5/1/2025','city':'dhaka','temperature':75,'humidity':80},
    {'date':'5/1/2025','city':'dhaka','temperature':78,'humidity':83},
    {'date':'5/2/2025','city':'dhaka','temperature':82,'humidity':85},
    {'date':'5/2/2025','city':'dhaka','temperature':80,'humidity':28}
])

df

       date      city  temperature  humidity
0  5/1/2025  new york           65        56
1  5/1/2025  new york           61        54
2  5/2/2025  new york           70        60
3  5/2/2025  new york           72        62
4  5/1/2025     dhaka           75        80
5  5/1/2025     dhaka           78        83
6  5/2/2025     dhaka           82        85
7  5/2/2025     dhaka           80        28

In [4]:
df

       date      city  temperature  humidity
0  5/1/2025  new york           65        56
1  5/1/2025  new york           61        54
2  5/2/2025  new york           70        60
3  5/2/2025  new york           72        62
4  5/1/2025     dhaka           75        80
5  5/1/2025     dhaka           78        83
6  5/2/2025     dhaka           82        85
7  5/2/2025     dhaka           80        28

# pivot_table

In [5]:
df.pivot_table(index='city', columns='date')

         humidity          temperature
date     5/1/2025 5/2/2025    5/1/2025 5/2/2025
city
dhaka        81.5     56.5        76.5     81.0
new york     55.0     61.0        63.0     71.0

In [6]:
df.pivot_table(index='city', columns='date',aggfunc="sum")

         humidity          temperature
date     5/1/2025 5/2/2025    5/1/2025 5/2/2025
city
dhaka         163      113         153      162
new york      110      122         126      142

In [7]:
df.pivot_table(index='city', columns='date',margins=True)

         humidity                temperature
date     5/1/2025 5/2/2025   All    5/1/2025 5/2/2025     All
city
dhaka       81.50    56.50  69.0       76.50     81.0  78.750
new york    55.00    61.00  58.0       63.00     71.0  67.000
All         68.25    58.75  63.5       69.75     76.0  72.875

In [8]:
df = pd.DataFrame([
    {'date':'5/1/2025','city':'new york','temperature':65,'humidity':56},
    {'date':'5/2/2025','city':'new york','temperature':61,'humidity':54},
    {'date':'5/3/2025','city':'new york','temperature':70,'humidity':60},
    {'date':'5/1/2025','city':'new york','temperature':72,'humidity':62},
    {'date':'5/2/2025','city':'new york','temperature':75,'humidity':80},
    {'date':'5/3/2025','city':'new york','temperature':78,'humidity':83},
   
])
df

       date      city  temperature  humidity
0  5/1/2025  new york           65        56
1  5/2/2025  new york           61        54
2  5/3/2025  new york           70        60
3  5/1/2025  new york           72        62
4  5/2/2025  new york           75        80
5  5/3/2025  new york           78        83

In [11]:
df['date']=pd.to_datetime(df['date'])
type(df['date'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [12]:
df.pivot_table(index=pd.Grouper(freq='M',key='date'),columns='city')

/tmp/ipykernel_34751/3780491757.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df.pivot_table(index=pd.Grouper(freq='M',key='date'),columns='city')

             humidity temperature
city         new york    new york
date
2025-05-31  65.833333   70.166667