# Read database records into pandas dataframe and write it back

# will will cover

pd.read_sql_table
pd.read_sql_query
df.to_sql
pd.read_sql(which is just a wrapper for first two method)

In [1]:
import pandas as pd
from sqlalchemy import create_engine
from pandas.io import sql

In [7]:
engine = create_engine("mysql+pymysql://{user}:{pw}@localhost:3306/{db}"
                      .format(user="root",
                             pw="Root%401234",
                              db="application"
                             )
                      )

In [8]:
try:
    connceton = engine.connect()
    print("successfull")
except Exception as e:
    print("error message",e)

successfull

In [12]:
df = pd.read_sql_table('customers', engine, columns=['name','phone_number'])

In [13]:
df

      name phone_number
0     atik  01768806574
1  tariful  01768532268
2    faruk  01235563653
3     atik  01768806574
4  tariful  01768532268
5    faruk  01235563653

In [16]:
query='''
SELECT
customers.name,
customers.phone_number,

orders.name AS order_name,
orders.amount

from customers
inner join orders
    ON customers.id = orders.customer_id;

'''
df = pd.read_sql_query(query, engine)
df

      name phone_number order_name  amount
0     atik  01768806574    tariful     950
1  tariful  01768532268       atik      20
2    faruk  01235563653      faruk     120
3     atik  01768806574    tariful     950
4  tariful  01768532268       atik      20
5    faruk  01235563653      faruk     120

In [17]:
data = pd.DataFrame([
    {'Customer Name':'bulbul','Customer Phone':'232454545'},
    {'Customer Name':'shorif','Customer Phone':'232444545'},
    {'Customer Name':'roton','Customer Phone':'232455545'},
    {'Customer Name':'sohel','Customer Phone':'2222454545'},
    {'Customer Name':'akbor','Customer Phone':'23245333545'},
    {'Customer Name':'rakib','Customer Phone':'238884545'},
])

data

  Customer Name Customer Phone
0        bulbul      232454545
1        shorif      232444545
2         roton      232455545
3         sohel     2222454545
4         akbor    23245333545
5         rakib      238884545

In [20]:
data.rename(columns={
    'Customer Name':'name',
    'Customer Phone':'phone_number'
}, inplace=True)

data #	 inplace=True এর মানে হলো, এই পরিবর্তনটা মূল data DataFrame-এ সরাসরি হয়ে যাবে — আলাদা করে কিছু রিটার্ন করার দরকার নেই

     name phone_number
0  bulbul    232454545
1  shorif    232444545
2   roton    232455545
3   sohel   2222454545
4   akbor  23245333545
5   rakib    238884545

In [21]:
data.to_sql(
name='customers',
    con=engine,
    index=False,
    if_exists='append'
    
)

6

In [23]:
pd.read_sql('customers',engine)

     id     name phone_number
0   1.0     atik  01768806574
1   2.0  tariful  01768532268
2   3.0    faruk  01235563653
3   1.0     atik  01768806574
4   2.0  tariful  01768532268
5   3.0    faruk  01235563653
6   NaN   bulbul    232454545
7   NaN   shorif    232444545
8   NaN    roton    232455545
9   NaN    sohel   2222454545
10  NaN    akbor  23245333545
11  NaN    rakib    238884545

In [24]:
query='''
SELECT
customers.name,
customers.phone_number,

orders.name AS order_name,
orders.amount

from customers
inner join orders
    ON customers.id = orders.customer_id;

'''

pd.read_sql(query,engine)

      name phone_number order_name  amount
0     atik  01768806574    tariful     950
1  tariful  01768532268       atik      20
2    faruk  01235563653      faruk     120
3     atik  01768806574    tariful     950
4  tariful  01768532268       atik      20
5    faruk  01235563653      faruk     120