In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('/home/catpc/Downloads/Weather_data.csv')

In [2]:
df

          day temperature windspeed  event
0  2017-01-07        32 F     7 mph   Rain
1  2017-01-01        9999     6 mph   Rain
2  2017-01-02          35         7      0
3  2017-01-03          28     -8888   Snow
4  2017-01-04        9999         7      0
5  2017-01-05          32         4   Rain
6  2017-01-06          32         2  Sunny

In [3]:
import numpy as np

new_df = df.replace({
    'temperature': {9999: np.NaN},
    'event': {'0': np.NaN},
    'windspeed': {-8888: np.NaN}
})

new_df

          day temperature windspeed  event
0  2017-01-07        32 F     7 mph   Rain
1  2017-01-01        9999     6 mph   Rain
2  2017-01-02          35         7    NaN
3  2017-01-03          28     -8888   Snow
4  2017-01-04        9999         7    NaN
5  2017-01-05          32         4   Rain
6  2017-01-06          32         2  Sunny

In [4]:
new_df = df.replace({
    -9999: np.NaN,
    'No Event' : 'Sunny',
    
})

new_df

          day temperature windspeed  event
0  2017-01-07        32 F     7 mph   Rain
1  2017-01-01        9999     6 mph   Rain
2  2017-01-02          35         7      0
3  2017-01-03          28     -8888   Snow
4  2017-01-04        9999         7      0
5  2017-01-05          32         4   Rain
6  2017-01-06          32         2  Sunny

In [5]:
df

          day temperature windspeed  event
0  2017-01-07        32 F     7 mph   Rain
1  2017-01-01        9999     6 mph   Rain
2  2017-01-02          35         7      0
3  2017-01-03          28     -8888   Snow
4  2017-01-04        9999         7      0
5  2017-01-05          32         4   Rain
6  2017-01-06          32         2  Sunny

In [6]:
new1_df = df.replace({
      9999 : np.NaN,
     -8888:np.NaN,
    'No Event' : 'Sunny',
})

new1_df

          day temperature windspeed  event
0  2017-01-07        32 F     7 mph   Rain
1  2017-01-01        9999     6 mph   Rain
2  2017-01-02          35         7      0
3  2017-01-03          28     -8888   Snow
4  2017-01-04        9999         7      0
5  2017-01-05          32         4   Rain
6  2017-01-06          32         2  Sunny

In [7]:
new_df = df.replace('[A-Za-z]','',regex=True)
new_df

          day temperature windspeed event
0  2017-01-07         32         7
1  2017-01-01        9999        6
2  2017-01-02          35         7     0
3  2017-01-03          28     -8888
4  2017-01-04        9999         7     0
5  2017-01-05          32         4
6  2017-01-06          32         2

In [8]:
new_df = df.replace({
    'temperature':'[A-Za-z]',
    'windspeed':'[A-Za-z]',
},'',regex=True)
new_df

          day temperature windspeed  event
0  2017-01-07         32         7    Rain
1  2017-01-01        9999        6    Rain
2  2017-01-02          35         7      0
3  2017-01-03          28     -8888   Snow
4  2017-01-04        9999         7      0
5  2017-01-05          32         4   Rain
6  2017-01-06          32         2  Sunny

In [9]:
df = pd.DataFrame({
    'score': ['exceptional', 'average','good','poor','average','exceptional'],
    'student':['rob','maya','parthiv','tom','julian','erica']
    
})
df

         score  student
0  exceptional      rob
1      average     maya
2         good  parthiv
3         poor      tom
4      average   julian
5  exceptional    erica

In [12]:
new1 = df.replace(['poor','average','good','exceptional'],[1,2,3,4])
new1

/tmp/ipykernel_11086/1963002716.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  new1 = df.replace(['poor','average','good','exceptional'],[1,2,3,4])

   score  student
0      4      rob
1      2     maya
2      3  parthiv
3      1      tom
4      2   julian
5      4    erica