# melt is used to transform or reshape data

In [13]:
import pandas as pd
df = pd.DataFrame([
    {'day':'Monday','chicago':'32','chennal':75,'berlin':41},
     {'day':'Tuesday','chicago':'32','chennal':75,'berlin':41},
     {'day':'Wednesday','chicago':'32','chennal':75,'berlin':41},
     {'day':'Thursday','chicago':'32','chennal':75,'berlin':41},
     {'day':'Friday','chicago':'32','chennal':75,'berlin':41},
     {'day':'Saturday','chicago':'32','chennal':75,'berlin':41},
     {'day':'Sunday','chicago':'32','chennal':75,'berlin':41},
])

df

         day chicago  chennal  berlin
0     Monday      32       75      41
1    Tuesday      32       75      41
2  Wednesday      32       75      41
3   Thursday      32       75      41
4     Friday      32       75      41
5   Saturday      32       75      41
6     Sunday      32       75      41

In [14]:
df1 = pd.melt(df, id_vars=["day"])
df1

          day variable value
0      Monday  chicago    32
1     Tuesday  chicago    32
2   Wednesday  chicago    32
3    Thursday  chicago    32
4      Friday  chicago    32
5    Saturday  chicago    32
6      Sunday  chicago    32
7      Monday  chennal    75
8     Tuesday  chennal    75
9   Wednesday  chennal    75
10   Thursday  chennal    75
11     Friday  chennal    75
12   Saturday  chennal    75
13     Sunday  chennal    75
14     Monday   berlin    41
15    Tuesday   berlin    41
16  Wednesday   berlin    41
17   Thursday   berlin    41
18     Friday   berlin    41
19   Saturday   berlin    41
20     Sunday   berlin    41

In [16]:
df1 = pd.melt(df, id_vars=["day"])
df1[df1['variable']=='chicago']

         day variable value
0     Monday  chicago    32
1    Tuesday  chicago    32
2  Wednesday  chicago    32
3   Thursday  chicago    32
4     Friday  chicago    32
5   Saturday  chicago    32
6     Sunday  chicago    32

In [17]:
df1 = pd.melt(df, id_vars=["day"])
df1[df1['variable']=='berlin']

          day variable value
14     Monday   berlin    41
15    Tuesday   berlin    41
16  Wednesday   berlin    41
17   Thursday   berlin    41
18     Friday   berlin    41
19   Saturday   berlin    41
20     Sunday   berlin    41

In [20]:
df1 = pd.melt(df, id_vars=["day"],var_name='city',value_name='temperature')
df1

          day     city temperature
0      Monday  chicago          32
1     Tuesday  chicago          32
2   Wednesday  chicago          32
3    Thursday  chicago          32
4      Friday  chicago          32
5    Saturday  chicago          32
6      Sunday  chicago          32
7      Monday  chennal          75
8     Tuesday  chennal          75
9   Wednesday  chennal          75
10   Thursday  chennal          75
11     Friday  chennal          75
12   Saturday  chennal          75
13     Sunday  chennal          75
14     Monday   berlin          41
15    Tuesday   berlin          41
16  Wednesday   berlin          41
17   Thursday   berlin          41
18     Friday   berlin          41
19   Saturday   berlin          41
20     Sunday   berlin          41