# stack and unstack

# what is stack

In [32]:
import pandas as pd

# ডেটা তৈরি
data = {
    ('Price', 'Facebook'): [155, 150, 153, 155, 156],
    ('Price', 'Google'): [955, 987, 963, 1000, 1012],
    ('Price', 'Microsoft'): [66, 69, 62, 61, 66],
    ('Price to earnings ratio (P/E)', 'Facebook'): [37.10, 36.98, 36.78, 36.11, 37.07],
    ('Price to earnings ratio (P/E)', 'Google'): [32.0, 31.3, 31.7, 31.2, 30.0],
    ('Price to earnings ratio (P/E)', 'Microsoft'): [30.31, 30.56, 30.40, 30.11, 31.00],
}
data

{('Price', 'Facebook'): [155, 150, 153, 155, 156],
 ('Price', 'Google'): [955, 987, 963, 1000, 1012],
 ('Price', 'Microsoft'): [66, 69, 62, 61, 66],
 ('Price to earnings ratio (P/E)', 'Facebook'): [37.1,
  36.98,
  36.78,
  36.11,
  37.07],
 ('Price to earnings ratio (P/E)', 'Google'): [32.0, 31.3, 31.7, 31.2, 30.0],
 ('Price to earnings ratio (P/E)', 'Microsoft'): [30.31,
  30.56,
  30.4,
  30.11,
  31.0]}

In [29]:
data.to_csv('new1.csv')

In [31]:
index = pd.date_range(start='2025-06-05',periods=5,freq='D')

In [33]:
df = pd.DataFrame(data, index=index)

In [34]:
df

              Price                  Price to earnings ratio (P/E)         \
           Facebook Google Microsoft                      Facebook Google
2025-06-05      155    955        66                         37.10   32.0
2025-06-06      150    987        69                         36.98   31.3
2025-06-07      153    963        62                         36.78   31.7
2025-06-08      155   1000        61                         36.11   31.2
2025-06-09      156   1012        66                         37.07   30.0


           Microsoft
2025-06-05     30.31
2025-06-06     30.56
2025-06-07     30.40
2025-06-08     30.11
2025-06-09     31.00

In [35]:
df.stack()

/tmp/ipykernel_34751/3977694045.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df.stack()

                      Price  Price to earnings ratio (P/E)
2025-06-05 Facebook     155                          37.10
           Google       955                          32.00
           Microsoft     66                          30.31
2025-06-06 Facebook     150                          36.98
           Google       987                          31.30
           Microsoft     69                          30.56
2025-06-07 Facebook     153                          36.78
           Google       963                          31.70
           Microsoft     62                          30.40
2025-06-08 Facebook     155                          36.11
           Google      1000                          31.20
           Microsoft     61                          30.11
2025-06-09 Facebook     156                          37.07
           Google      1012                          30.00
           Microsoft     66                          31.00

In [37]:
stack_df = df.stack(level=0)
stack_df

/tmp/ipykernel_34751/1359392305.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  stack_df = df.stack(level=0)

                                          Facebook  Google  Microsoft
2025-06-05 Price                            155.00   955.0      66.00
           Price to earnings ratio (P/E)     37.10    32.0      30.31
2025-06-06 Price                            150.00   987.0      69.00
           Price to earnings ratio (P/E)     36.98    31.3      30.56
2025-06-07 Price                            153.00   963.0      62.00
           Price to earnings ratio (P/E)     36.78    31.7      30.40
2025-06-08 Price                            155.00  1000.0      61.00
           Price to earnings ratio (P/E)     36.11    31.2      30.11
2025-06-09 Price                            156.00  1012.0      66.00
           Price to earnings ratio (P/E)     37.07    30.0      31.00

In [38]:
stack_df.unstack()

           Facebook                                Google  \
              Price Price to earnings ratio (P/E)   Price
2025-06-05    155.0                         37.10   955.0
2025-06-06    150.0                         36.98   987.0
2025-06-07    153.0                         36.78   963.0
2025-06-08    155.0                         36.11  1000.0
2025-06-09    156.0                         37.07  1012.0

                                         Microsoft  \
           Price to earnings ratio (P/E)     Price
2025-06-05                          32.0      66.0
2025-06-06                          31.3      69.0
2025-06-07                          31.7      62.0
2025-06-08                          31.2      61.0
2025-06-09                          30.0      66.0


           Price to earnings ratio (P/E)
2025-06-05                         30.31
2025-06-06                         30.56
2025-06-07                         30.40
2025-06-08                         30.11
2025-06-09                         31.00

In [ ]:
df2 =pd.read

In [39]:
import pandas as pd

# MultiIndex columns definition
columns = pd.MultiIndex.from_tuples([
    ('Price Ratios', 'Price', 'Facebook'),
    ('Price Ratios', 'Price', 'Google'),
    ('Price Ratios', 'Price', 'Microsoft'),
    ('Price Ratios', 'Price to earnings ratio (P/E)', 'Facebook'),
    ('Price Ratios', 'Price to earnings ratio (P/E)', 'Google'),
    ('Price Ratios', 'Price to earnings ratio (P/E)', 'Microsoft'),
    ('Income Statement', 'Net Sales', 'Facebook'),
    ('Income Statement', 'Net Sales', 'Google'),
    ('Income Statement', 'Net Sales', 'Microsoft'),
    ('Income Statement', 'Net Profit', 'Facebook'),
    ('Income Statement', 'Net Profit', 'Google'),
    ('Income Statement', 'Net Profit', 'Microsoft'),
])

# Row index
index = ['Q1 2016', 'Q2 2016', 'Q3 2016', 'Q4 2016', 'Q1 2017']

# Data values
data = [
    [155, 955, 66, 37.10, 32.0, 30.31, 2.6, 20, 18.70, 0.80, 5.43, 4.56],
    [150, 987, 69, 36.98, 31.3, 30.56, 3.1, 22, 21.30, 0.97, 5.89, 5.10],
    [153, 963, 62, 36.78, 31.7, 30.46, 4.3, 24, 21.45, 1.20, 6.10, 5.43],
    [155, 1000, 61, 36.11, 31.2, 30.11, 6.7, 26, 21.88, 1.67, 6.50, 5.89],
    [156, 1012, 66, 37.07, 30.0, 31.00, 8.1, 31, 22.34, 2.03, 6.40, 6.09],
]

# Create DataFrame
df = pd.DataFrame(data, index=index, columns=columns)

# Display
print(df)

        Price Ratios                                                        \
               Price                  Price to earnings ratio (P/E)
            Facebook Google Microsoft                      Facebook Google
Q1 2016          155    955        66                         37.10   32.0
Q2 2016          150    987        69                         36.98   31.3
Q3 2016          153    963        62                         36.78   31.7
Q4 2016          155   1000        61                         36.11   31.2
Q1 2017          156   1012        66                         37.07   30.0

                  Income Statement                                     \
                         Net Sales                  Net Profit
        Microsoft         Facebook Google Microsoft   Facebook Google
Q1 2016     30.31              2.6     20     18.70       0.80   5.43
Q2 2016     30.56              3.1     22     21.30       0.97   5.89
Q3 2016     30.46              4.3     24     21.45       1.20   6.10
Q4 2016     30.11              6.7     26     21.88       1.67   6.50
Q1 2017     31.00              8.1     31     22.34       2.03   6.40



        Microsoft
Q1 2016      4.56
Q2 2016      5.10
Q3 2016      5.43
Q4 2016      5.89
Q1 2017      6.09

In [40]:
df.stack()

/tmp/ipykernel_34751/3977694045.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df.stack()

                  Price Ratios                               Income Statement  \
                         Price Price to earnings ratio (P/E)        Net Sales
Q1 2016 Facebook           155                         37.10             2.60
        Google             955                         32.00            20.00
        Microsoft           66                         30.31            18.70
Q2 2016 Facebook           150                         36.98             3.10
        Google             987                         31.30            22.00
        Microsoft           69                         30.56            21.30
Q3 2016 Facebook           153                         36.78             4.30
        Google             963                         31.70            24.00
        Microsoft           62                         30.46            21.45
Q4 2016 Facebook           155                         36.11             6.70
        Google            1000                         31.20            26.00
        Microsoft           61                         30.11            21.88
Q1 2017 Facebook           156                         37.07             8.10
        Google            1012                         30.00            31.00
        Microsoft           66                         31.00            22.34


                  Net Profit
Q1 2016 Facebook        0.80
        Google          5.43
        Microsoft       4.56
Q2 2016 Facebook        0.97
        Google          5.89
        Microsoft       5.10
Q3 2016 Facebook        1.20
        Google          6.10
        Microsoft       5.43
Q4 2016 Facebook        1.67
        Google          6.50
        Microsoft       5.89
Q1 2017 Facebook        2.03
        Google          6.40
        Microsoft       6.09

In [41]:
df.stack(level=0)

/tmp/ipykernel_34751/4116294391.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df.stack(level=0)

                            Price                    \
                         Facebook  Google Microsoft
Q1 2016 Income Statement      NaN     NaN       NaN
        Price Ratios        155.0   955.0      66.0
Q2 2016 Income Statement      NaN     NaN       NaN
        Price Ratios        150.0   987.0      69.0
Q3 2016 Income Statement      NaN     NaN       NaN
        Price Ratios        153.0   963.0      62.0
Q4 2016 Income Statement      NaN     NaN       NaN
        Price Ratios        155.0  1000.0      61.0
Q1 2017 Income Statement      NaN     NaN       NaN
        Price Ratios        156.0  1012.0      66.0

                         Price to earnings ratio (P/E)                   \
                                              Facebook Google Microsoft
Q1 2016 Income Statement                           NaN    NaN       NaN
        Price Ratios                             37.10   32.0     30.31
Q2 2016 Income Statement                           NaN    NaN       NaN
        Price Ratios                             36.98   31.3     30.56
Q3 2016 Income Statement                           NaN    NaN       NaN
        Price Ratios                             36.78   31.7     30.46
Q4 2016 Income Statement                           NaN    NaN       NaN
        Price Ratios                             36.11   31.2     30.11
Q1 2017 Income Statement                           NaN    NaN       NaN
        Price Ratios                             37.07   30.0     31.00

                         Net Sales                  Net Profit         \
                          Facebook Google Microsoft   Facebook Google
Q1 2016 Income Statement       2.6   20.0     18.70       0.80   5.43
        Price Ratios           NaN    NaN       NaN        NaN    NaN
Q2 2016 Income Statement       3.1   22.0     21.30       0.97   5.89
        Price Ratios           NaN    NaN       NaN        NaN    NaN
Q3 2016 Income Statement       4.3   24.0     21.45       1.20   6.10
        Price Ratios           NaN    NaN       NaN        NaN    NaN
Q4 2016 Income Statement       6.7   26.0     21.88       1.67   6.50
        Price Ratios           NaN    NaN       NaN        NaN    NaN
Q1 2017 Income Statement       8.1   31.0     22.34       2.03   6.40
        Price Ratios           NaN    NaN       NaN        NaN    NaN


                         Microsoft
Q1 2016 Income Statement      4.56
        Price Ratios           NaN
Q2 2016 Income Statement      5.10
        Price Ratios           NaN
Q3 2016 Income Statement      5.43
        Price Ratios           NaN
Q4 2016 Income Statement      5.89
        Price Ratios           NaN
Q1 2017 Income Statement      6.09
        Price Ratios           NaN